name: CI workflow

on:
  pull_request:
    branches:
      - "main"
      - "staging"
      - "develop"

jobs:
  Static-Code-Analysis:
    concurrency:
      group: ci-${{ github.ref }}-${{ github.run_id }}
      cancel-in-progress: true
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run linter check
        if: ${{ always() }}
        run: npm run eslint
      - name: Run types check
        if: ${{ always() }}
        run: npm run types:check
